config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :infos
  devise_for :users
  resources :crusts
  resources :recipes
  resources :ingredients

  resources :pizzas
  root 'pizzas#main'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	belongs_to :ingredient1, :class_name => 'Ingredient'
	belongs_to :ingredient2, :class_name => 'Ingredient'
	belongs_to :ingredient3, :class_name => 'Ingredient'
	has_many :pizza
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :value, :ingredient1_id, :ingredient2_id, :ingredient3_id)
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :recipe_title %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.number_field :value, id: :recipe_value %>
  </div>
	
   <div class="field">
    <%= form.label :ingredient1 %>
    <%= form.select :ingredient1_id, options_for_select(Ingredient.all.map{|s|[s.name, s.id]}), id: :recipe_ingredient_id %>
   </div>

   <div class="field">
    <%= form.label :ingredient2 %>
    <%= form.select :ingredient2_id, options_for_select(Ingredient.all.map{|s|[s.name, s.id]}), id: :recipe_ingredient_id %>
   </div>

   <div class="field">
    <%= form.label :ingredient3 %>
    <%= form.select :ingredient3_id, options_for_select(Ingredient.all.map{|s|[s.name, s.id]}), id: :recipe_ingredient_id %>
   </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Value</th>
      <th>Ingredient 1</th>
      <th>Ingredient 2</th>
      <th>Ingredient 3</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.value %></td>
	<td><%= recipe.ingredient1.name %></td>
	<td><%= recipe.ingredient2.name %></td>
	<td><%= recipe.ingredient3.name %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Value:</strong>
  <%= @recipe.value %>
</p>

<p>
  <strong>Ingrediente 1:</strong>
  <%= @recipe.ingredient1.name %>
</p>

<p>
  <strong>Ingrediente 2:</strong>
  <%= @recipe.ingredient2.name %>
</p>

<p>
  <strong>Ingrediente 3:</strong>
  <%= @recipe.ingredient3.name %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>