config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :infos
  devise_for :users
  resources :crusts
  resources :recipes
  resources :ingredients

  resources :pizzas
  root 'pizzas#main'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pizza.rb
class Pizza < ApplicationRecord
	belongs_to :recipe
	belongs_to :crust
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  before_action :set_pizza, only: [:show, :edit, :update, :destroy]

  # GET /pizzas
  # GET /pizzas.json

  def main

  end
 
  def index
    @pizzas = Pizza.all
  end

  # GET /pizzas/1
  # GET /pizzas/1.json
  def show
  end

  # GET /pizzas/new
  def new
    @pizza = Pizza.new
  end

  # GET /pizzas/1/edit
  def edit
  end

  # POST /pizzas
  # POST /pizzas.json
  def create
    @pizza = Pizza.new(pizza_params)

    respond_to do |format|
      if @pizza.save
        format.html { redirect_to @pizza, notice: 'Pizza was successfully created.' }
        format.json { render :show, status: :created, location: @pizza }
      else
        format.html { render :new }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pizzas/1
  # PATCH/PUT /pizzas/1.json
  def update
    respond_to do |format|
      if @pizza.update(pizza_params)
        format.html { redirect_to @pizza, notice: 'Pizza was successfully updated.' }
        format.json { render :show, status: :ok, location: @pizza }
      else
        format.html { render :edit }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pizzas/1
  # DELETE /pizzas/1.json
  def destroy
    @pizza.destroy
    respond_to do |format|
      format.html { redirect_to pizzas_url, notice: 'Pizza was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pizza
      @pizza = Pizza.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pizza_params
      params.require(:pizza).permit(:name, :description, :recipe_id, :crust_id)
    end
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/views/pizzas/_form.html.erb
<%= form_with(model: pizza, local: true) do |form| %>
  <% if pizza.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pizza.errors.count, "error") %> prohibited this pizza from being saved:</h2>

      <ul>
      <% pizza.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :pizza_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :pizza_description %>
  </div>
	
  <div class="field">
    <%= form.label :recipe %>
    <%= form.select :recipe_id, options_for_select(Recipe.all.map{|s|[s.title, s.id]}), id: :pizza_recipe_id %>
  </div>

  <div class="field">
    <%= form.label :crust %>
    <%= form.select :crust_id, options_for_select(Crust.all.map{|s|[s.name, s.id]}), id: :pizza_crust_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pizzas/edit.html.erb
<h1>Editing Pizza</h1>

<%= render 'form', pizza: @pizza %>

<%= link_to 'Show', @pizza %> |
<%= link_to 'Back', pizzas_path %>

app/views/pizzas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pizzas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Recipe</th>
      <th>Crust</th>
      <th>Value</th>
      <th>Description</th>

      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @pizzas.each do |pizza| %>
      <tr>
        <td><%= pizza.name %></td>
        <td><%= pizza.recipe.title %></td>
        <td><%= pizza.crust.name %></td>
        <td><%= pizza.crust.value + pizza.recipe.value %></td>
        <td><%= pizza.description %></td>
        <td><%= link_to 'Show', pizza %></td>
        <td><%= link_to 'Edit', edit_pizza_path(pizza) %></td>
        <td><%= link_to 'Destroy', pizza, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pizza', new_pizza_path %>
<%= link_to 'Back', root_path %>

app/views/pizzas/main.html.erb
<h2> Welcome to Mama Joe's </h2>
<div>
	<li><%= link_to 'Pizzas Catalog', pizzas_path %></li>
	<li><%= link_to 'Recipes Catalog', recipes_path %></li>
	<li><%= link_to 'Ingredients Catalog', ingredients_path %></li>
	<li><%= link_to 'Crusts Catalog', crusts_path %></li>
</div>

app/views/pizzas/new.html.erb
<h1>New Pizza</h1>

<%= render 'form', pizza: @pizza %>

<%= link_to 'Back', pizzas_path %>

app/views/pizzas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pizza.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pizza.description %>
</p>

<p>
  <strong>Pizza value:</strong>
  <%= @pizza.recipe.value + @pizza.crust.value  %>
</p>


<p>
  <strong>Crust:</strong>
  <%= @pizza.crust.name %>
</p>
<p>
  <strong>Crust value:</strong>
  <%= @pizza.crust.value %>
</p>
<p>
  <strong>Recipe:</strong>
  <%= @pizza.recipe.title %>

</p>
<p>
  <strong>Recipe value:</strong>
  <%= @pizza.recipe.value %>
</p>
<p>
  <strong>Ingredient 1:</strong>
  <%= @pizza.recipe.ingredient1.name %>
</p>
<p>
  <strong>Ingredient 2:</strong>
  <%= @pizza.recipe.ingredient2.name %>
</p>
<p>
  <strong>Ingredient 3:</strong>
  <%= @pizza.recipe.ingredient3.name %>
</p>


<%= link_to 'Edit', edit_pizza_path(@pizza) %> |
<%= link_to 'Back', pizzas_path %>